### ISSUE TITLE
Multiple submits (and submit feedback)

### ISSUE THREAD

**Issue by QuentinRoy** [spiral-project/ihatemoney#86] opened 2012-07-10 21:55 UTC
I just noticed that you can submit multiple time the same bill if you do not wait the server's answer. I think it should be blocked. I just did the following mistake :
- fill in the bill form
- Press 'enter' to send
- There is no feedback so I thought "Oh... Enter doesn't work"
- Pressed 'Submit'
- "Why the *\* did it create my bill twice?"

**Comment by JocelynDelalande** [comment] 2015-08-21 03:37
Has it been fixed since ? I can't reproduce, even adding time.sleep(2) on backend view so that it takes long to respond

**Comment by QuentinRoy** [comment] 2015-08-23 16:01
It seems very unfixed in the ihatemoney.org version (I just clicked multiple times on the submit button).

![screen shot 2015-08-23 at 17 54 28](https://cloud.githubusercontent.com/assets/728801/9428970/c864d868-49c0-11e5-9069-6f26c64e41d7.png)

**Comment by ametaireau** [comment] 2015-08-24 10:06
Current deployed version is 42dd9d54a89b7ef8a015b20d8a979e835fa87b09. Also, this issue is not fixed in master.

**Comment by ametaireau** [comment] 2015-08-24 10:07
Changes since last deploy: https://github.com/spiral-project/ihatemoney/compare/42dd9d54a89b7ef8a015b20d8a979e835fa87b09...master

**Comment by almet** [comment] 2017-02-01 22:02
Fixed, closing.

**Closed by almet** 2017-02-01 22:02 UTC
Labels: bug
