### ISSUE TITLE
Testing with tox is broken

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#1012] opened 2022-04-02 23:17 UTC
See all recent pull requests: CI testing is broken.

I can reproduce locally when testing with tox:

```
python3 -m venv /tmp/venv-ihm-tox
. /tmp/venv-ihm-tox/bin/activate
pip install -U pip
pip install -U tox
tox -e py
```

I end up with very weird errors.

Testing "manually" without tox works fine:

```
python3 -m venv /tmp/venv-ihm-tests
. /tmp/venv-ihm-tests/bin/activate
pip install -e .[dev]
py.test --pyargs ihatemoney.tests
```

I haven't been able to figure out what's wrong. At first I thought that was caused by a new version of pip (22.X), but even when downgrading pip tox keeps failing.

**Comment by almet** [comment] 2022-04-04 15:25
So, I tried to run again the `make test` after running tox manually and… I've got the tests failing. Not sure what's going on, but at least I can reproduce.

python3.{7,8,9} are failing, but python 3.6 is working well.

The installed package versions do not differ between the working run and the failing run. :thinking:

**Comment by almet** [comment] 2022-04-04 15:48
I don't have much time today to look more into this though…

**Comment by zorun** [comment] 2022-04-04 16:07
> E           alembic.util.exc.CommandError: Path doesn't exist: '/home/alexis/dev/ihatemoney/.tox/py/lib/python3.10/site-packages/ihatemoney/migrations'.  Please use the 'init' command to create a new scripts folder.

Yes, I had the same kind of errors. I "fixed" it by adding `__init__.py` files in `migrations/`, but then I had other very weird errors on all tests.

This is what led me to believe it was related to wheel building or pip installation, but I haven't got to the bottom of it...

**Comment by Glandos** [comment] 2022-04-10 21:21
It is related to wheel building. The wheel built with tox doesn't contain any `static`, `templates`, etc., directories. The wheel I build when installing into a virtualenv made with my system package (Debian unstable) have all of them.
I strace the creation, and they are all unlinked. I didn't have the time to track where the changed behavior occurred exactly, so this comment is also a reminder for myself.

**Comment by Glandos** [comment] 2022-04-15 20:47
Bingo: https://github.com/pypa/virtualenv/issues/2327

**Comment by Glandos** [comment] 2022-04-15 21:35
Closing, since it autosolved with a new version of virtualenv.

**Closed by Glandos** 2022-04-15 21:35 UTC

**Comment by zorun** [comment] 2022-04-19 22:05
Well done, good detective job, as usual!

It's a bit frustrating that it fixed itself "magically", but at least we kind of know where this comes from.
