### ISSUE TITLE
Add a refund button on settle page

### ISSUE THREAD

**Issue by LeoMouyna** [spiral-project/ihatemoney#493] opened 2019-10-14 08:41 UTC
At the end of each row we could add a "refund" button that will automatically generate a bill with exact amount from "who pays" to "to whom".

I don't know if you have another way to refund if so let me know !

**Comment by nishikeshKardak** [comment] 2019-10-15 03:00
Hey @LeoMouyna, I want to work on this issue. Can I?

**Comment by almet** [comment] 2019-10-15 11:17
There is no other way to create a refund, other than doing it manually. This proposition makes sense to me, adn has been already discussed in #137.

**Comment by almet** [comment] 2019-10-15 11:17
Closing as a dupe of #137 (but thanks for the input!)

**Closed by almet** 2019-10-15 11:17 UTC
