### ISSUE TITLE
Project history shows Internal Server Error 

### ISSUE THREAD

**Issue by Flo2410** [spiral-project/ihatemoney#1038] opened 2022-07-10 11:47 UTC
When I try to view the history of  my main project, I get an "Internal Server Error" (Error message below). The project that this happens with, was created in January 2021.  A project created recently does not have this issue. If I am remembering correctly, it did work in the beginning.
I am running the ihatemoney/ihatemoney:latest docker image. 

If you need some more information, feel free to ask me.

Log: 
```
ERROR [ihatemoney.run] Exception on /universe/history [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy_continuum/utils.py", line 28, in get_versioning_manager
    return cls.__versioning_manager__
AttributeError: type object 'NoneType' has no attribute '__versioning_manager__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/src/ihatemoney/web.py", line 783, in history
    history = get_history(g.project, human_readable_names=True)
  File "/src/ihatemoney/history.py", line 119, in get_history
    val_after = describe_version(version.payer)
  File "/src/ihatemoney/history.py", line 41, in describe_version
    return parent_class(type(version_obj)).__str__(version_obj)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy_continuum/utils.py", line 79, in parent_class
    return get_versioning_manager(version_cls).parent_class_map[version_cls]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy_continuum/utils.py", line 30, in get_versioning_manager
    raise ClassNotVersioned(cls.__name__)
sqlalchemy_continuum.exc.ClassNotVersioned: NoneType
```

**Comment by Glandos** [comment] 2022-07-17 15:04
That's weird, it seemed that the DB upgrade wasn't run properly. Are you able to share a stripped down version of your database?

**Comment by Flo2410** [comment] 2022-07-17 15:39
As I have no experience using SQL databases… Here is my hole SQLite .db file.

[ihatemoney-db.zip](https://github.com/spiral-project/ihatemoney/files/9127987/ihatemoney-db.zip)

**Comment by Glandos** [comment] 2022-07-21 21:43
I have the *why*: payer `1` and `2` are not recorded in `person_version` table, but on bill `96`, payer changed, and when it tries to fetch the payer attributes from `payer_version` table, it fails.
I tried to issues some SQL to restore that, but without success so far. I'll try to provide you something working.

However, I have clearly no idea why these transactions were not recorded. Or maybe deleted somehow… Did you remember something about history management?

**Comment by Flo2410** [comment] 2022-07-22 19:37
Thanks for your help. 
No, I can't remember that I have done anything with the history management. It definitely did work at some point in the past.

**Comment by Glandos** [comment] 2022-07-24 21:19
I have to announce that I won't be able to *restore* the history for this project. At least not completely.
**Technical**: sqlalchemy_continuum (the library that create the history) uses transaction_id and payer changes from bill with the person id that must be lower than the bill transaction id (to avoid displaying person attributes that were changed after the bill change itself). But the `transaction` table is full of sequential IDs, so there nowhere to insert the missing person transaction.

The only thing I can suggest is provide to you some sql statements to **delete** those history. History will be incomplete, as it will only shows that bills have been modified, without showing what. It happens on 10 bills in your project.
Note that this dirty fix will only works for existing bills. If other new bills are created after that, and the payer id is changed on those new bills for payer `1` or `2`, this will fail again… The best thing to do after that fix will be to create a new project, if possible…

Sorry for the inconvenience, but the root cause for this issue seems a little bit too deep for my available spare time.

**Comment by Flo2410** [comment] 2022-07-30 18:13
Okay… That's annoying, but not that big of a problem. Could you please send me the SQL statements.

**Comment by Glandos** [comment] 2022-08-09 16:41
You'll be happy to know that while this answer is very late, I found a better solution. Please stop IHateMoney, and run the following SQL statement:
```sql
INSERT INTO "person_version" VALUES (2, 'universe', 'Greg', 1, 1, 1, NULL, 0);
INSERT INTO "person_version" VALUES (1, 'universe', 'Flo', 1, 1, 1, NULL, 0);
```
Technical details: it will attach the creation of `Greg` and `Flo` to the first transaction (6th insert parameter, just before `NULL`), along with their bills that are also on the same transaction. I thought that transactions can only contains one type of modification, but this is false: one transaction can create a project **and** add a bill **and** add a payer at the same time.

@Flo2410 Please confirm that this works for you!

**Closed by Glandos** 2022-08-09 16:41 UTC

**Comment by Flo2410** [comment] 2022-08-29 16:23
Sorry for the late replay. 

It worked! 
Thanks alot.

**Comment by georgefst** [comment] 2022-11-12 15:15
I've hit this, using the hosted version. Any tips? This is the first time I've tried to open the history page.

**Comment by almet** [comment] 2022-12-11 13:30
@georgefst Can you help me reproduce? What's the name of your project?

**Comment by georgefst** [comment] 2022-12-11 22:42
> @georgefst Can you help me reproduce? What's the name of your project?

https://ihatemoney.org/aynhoe/history

**Comment by Glandos** [comment] 2023-01-08 15:02
@almet Were you able to fix this?
