### ISSUE TITLE
Private instance

### ISSUE THREAD

**Issue by Phyks** [spiral-project/ihatemoney#200] opened 2017-04-11 08:48 UTC
Hi,

It would be really useful to have some settings to make a private instance. Basically, this would disable the demo and prevent anyone from creating a new project.

Thanks!

**Comment by almet** [comment] 2017-04-11 12:18
Hi, thanks for opening an issue here. I believe this is a duplicate of https://github.com/spiral-project/ihatemoney/issues/108. The discussion would benefit from your input I believe, so don't hesitate to go there and comment, thanks!

**Closed by almet** 2017-04-11 12:18 UTC

**Comment by Phyks** [comment] 2017-04-11 13:53
Indeed, thanks for the pointer. I did a quick search but completely missed the other issue. Moving there :)
