### ISSUE TITLE
Be able to configure the number of person in the person list.

### ISSUE THREAD

**Issue by Natim** [spiral-project/ihatemoney#134] opened 2016-01-31 11:38 UTC
When going with couple, you want to count 2 people for some names and 1 for some other one.
Another way do to that would be to merge group people on the settle page to remove money transfert between people of the same couple for instance.

**Comment by almet** [comment] 2016-01-31 11:43
I believe this is a dupe of https://github.com/spiral-project/ihatemoney/pull/131.  Closing.

**Closed by almet** 2016-01-31 11:43 UTC

**Comment by Natim** [comment] 2016-02-08 10:34
Yes it might be, should we merge it?
