### ISSUE TITLE
[Feature] choose weight for each bill

### ISSUE THREAD

**Issue by moonshaadow** [spiral-project/ihatemoney#1124] opened 2023-01-10 14:49 UTC
Hi there, 
Thank's for this great app. I'm here because I was looking for a open source alternative  to **tricount**.
IMO the major missing feature is the ability to choose individual weight for each bill.

Here a picture to explain : 
![Capture d’écran du 2023-01-10 15-47-15](https://user-images.githubusercontent.com/29754932/211582540-89162e05-6acd-4917-abe7-339a28a451b8.png)

**Comment by Glandos** [comment] 2023-01-28 22:18
Hi @moonshaadow thanks for raising this issue. It's a duplicate of #471 but it seems to be useful to many people. In the meantime, you could subscribe to that issue to get notified!

**Closed by Glandos** 2023-01-28 22:18 UTC
