### ISSUE TITLE
Formular: Edit this member -> Submit Button Caption > Change to "Edit"

### ISSUE THREAD

**Issue by jkopka** [spiral-project/ihatemoney#529] opened 2020-02-04 09:24 UTC
In the form for editing a member, the caption of the submit button is "Add". That should be "Edit".

for example: https://ihatemoney.org/demo/members/4504/edit

**Comment by almet** [comment] 2020-02-05 09:51
Hey, thanks for taking the time to give us this feedback. I'm marking it as a good first bug, it should be fairly easy to change.

**Comment by jkopka** [comment] 2020-02-05 12:27
Ok, i would like to give it a try and fix this.

**Comment by almet** [comment] 2020-02-05 13:06
@jkopka neat! A cool way to start is to read [the contribution guidelines](https://ihatemoney.readthedocs.io/en/latest/contributing.html), but it should be pretty straightforward for this change.

I'll let you have a look at the code, if you need any help, don't hesitate to tell us, and we'll try to help :-)

**Comment by jkopka** [comment] 2020-02-07 09:54
Ok, i have fix it. How do i commit it? I get two errors when i run "make release":
- "You must provide a DEST_DIR"
- "/bin/sh: realpath: command not found"

You have an idea?

**Comment by almet** [comment] 2020-02-09 12:02
I don't understand why you're trying to run `make release`? It's meant to be used for people who can issue new releases (not you ;-)).

What are you trying to do?

**Comment by almet** [comment] 2020-02-13 20:27
@jkopka hey, are you still willing to work on this?

**Comment by jkopka** [comment] 2020-02-14 07:34
I'm on it. `make release` was mentioned in the guide. It's my first contribution for a projekt here on github.

**Comment by almet** [comment] 2020-02-14 09:23
Okay, no worries. I'm sorry if the contribution guide isn't clear enough. `Make release` is a command that's made for releasing the software to PyPI, so that users can find it there. 

It's not yet the step you are at :-)

Here are a few steps you can follow : 

1. Clone the project locally using git clone URLOFTHEREPO and create a branch to work on using `git checkout -b member-add-button`
2. Find the string you want to change / translate. It's in [this block](https://github.com/spiral-project/ihatemoney/blob/master/ihatemoney/templates/forms.html#L133-L143)
3. Change the text you want to change
4. Run `make update-translations` so that the new strings are detected
5. Open a pull request so we can review what you've done.

I hope this is clearer, and good luck!

**Comment by jkopka** [comment] 2020-02-17 19:55
Thank you.

I got it already changed. Now i am stucked at `make update-translations`.
I got this error:
`make: /bin/pybabel: No such file or directory`
I have pybabel installed, but it is under `./usr/local/bin/pybabel`.
To get the form fixed was the easy part for me. ;)

**Comment by almet** [comment] 2020-02-20 08:45
You probably need to run `make install-dev` first. Thanks for you patience ;-) I'll update the Makefile and the docs so it's simpler in the future.

**Comment by jkopka** [comment] 2020-02-24 19:41
ok, i've created the branch, have done all necessary changes, committed them locally. How can i create a pull request?

Thanks for all your help!

**Comment by almet** [comment] 2020-02-24 21:07
Here is a useful link :-) https://opensource.com/article/19/7/create-pull-request-github

**Comment by jkopka** [comment] 2020-03-02 18:58
I have crates and closed the pull request. What’s next?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by indatwood** [comment] 2020-04-05 11:49
@jkopka If the issue is fixed, then you should close it! Not sure if you have the right to do that?

**Comment by Glandos** [comment] 2020-04-07 15:06
The issue will be fixed with #539 but @LeoMouyna objected the comment I've made, and didn't answer yet, so I'm waiting for a reply.

**Closed** 2020-04-14 08:56 UTC
Labels: good first issue
