### ISSUE TITLE
Fix Layout on Mobile

### ISSUE THREAD

**Issue by brubrant** [spiral-project/ihatemoney#183] opened 2017-03-21 00:21 UTC
Hi,

After the update to TWBS 4 the it's hard the use the App on mobile. I use it a lot on my smartphone (right after I pay a bill that is shared) and now it is very hard as the "Add new Bill" is hidden under the navbar.

Looks like a problem with the columns on them (a ROW wrapping them may be necessary). Adding the row wrapper fix a bit, buy the maybe better to hide some elements that are making the navbar too tall.

**Comment by JocelynDelalande** [comment] 2017-03-21 08:07
@brubrant ihatemoney is simply not responsive at the moment. It still a task that has to be done by someone, see #113 .

Help on this point is more than welcome, by the way :-)

**Comment by JocelynDelalande** [comment] 2017-03-21 08:07
duplicate of #113

**Closed by JocelynDelalande** 2017-03-21 08:07 UTC
