### ISSUE TITLE
Legal disclaimer - About

### ISSUE THREAD

**Issue by Nartagnan** [spiral-project/ihatemoney#348] opened 2018-07-05 19:56 UTC
There is no link to a legal disclaimer.
It would be different for each instance, but I think it is a legal obligation. It could also indicate who and where the data is held, the license (because Github is ugly), etc...

**Comment by almet** [comment] 2018-07-06 09:39
Thanks! I've tagged this as a good first bug. Don't hesitate to take it over if you want!

**Comment by almet** [comment] 2018-08-05 17:00
Actually, I'm not sure exactly what I should do, and what is legally mandatory. Do you have more information on this, so we can update the ihatemoney instance and include terms of service etc?

**Comment by 35609902357** [comment] 2019-12-29 14:37
@almet A search engine will provide many answer on how to write terms and conditions, as a rule of thumb, the less data you collect, the least responsibility you have. No logs, nothing to share, nothing to be accountable for. That of course if the data on the server is encrypted and you can't access it without knowing the user's password, if you can access it that complicates the things a little bit.

**Comment by almet** [comment] 2020-01-02 15:16
@35609902357 Thanks for the follow up.

That's actually interesting, and I'm thinking about looking for a backend which would allow to encrypt the files with a secret derived from the password, or from something that's not known from the server operator.

We are in 2020, we actully should enforce this.

**Comment by Velismo** [comment] 2020-01-20 15:58
Hi! This is my first time cooperating. How can I Help you?

**Comment by Natim** [comment] 2020-01-20 16:08
If you want to write a legal discamer that describe the list of private information this software stores it would be great.

Now that I think about it we only keep the email address of the project creator.

**Comment by Velismo** [comment] 2020-01-20 16:14
Yeah, sure. I can do that. Sounds good for me.

**Comment by Velismo** [comment] 2020-01-20 16:29
Where I can find the info to create the disclaimer?

**Comment by Natim** [comment] 2020-01-20 16:43
According to @35609902357 : 

> A search engine will provide many answer on how to write terms and conditions, as a rule of thumb, the less data you collect, the least responsibility you have. No logs, nothing to share, nothing to be accountable for.

**Comment by Velismo** [comment] 2020-01-20 18:34
Hey @Natim  I have a suggestion. How can i send it tot you?

**Comment by indatwood** [comment] 2020-04-22 15:17
Hi @Velismo you can comment here if you want :-)

**Comment by CubixPro** [comment] 2020-05-21 06:55
Can I work on this?

**Comment by Velismo** [comment] 2020-05-21 07:45
Yep. No problem for me.

**Comment by Glandos** [comment] 2020-05-21 09:38
@CubixPro thanks you for taking time to work on this!
Don't hesitate to send some prototypes first, because maybe we just want to make it optional, since we like to keep this project as light as possible.

**Comment by CubixPro** [comment] 2020-05-21 09:51
Okay 
I am a bit confused as to where exactly to add the disclaimer?

**Comment by Glandos** [comment] 2020-05-24 18:44
You're asking the right question :+1: 
In my mind, we shouldn't reinvent the wheel: put a link in the footer, leading to a new page with legal stuff in it.

**Comment by almet** [comment] 2021-10-17 14:20
Duplicate of #761

**Closed by almet** 2021-10-17 14:20 UTC
Labels: feature request, good first issue, low hanging fruits
