### ISSUE TITLE
Problem with total spend

### ISSUE THREAD

**Issue by gauthier12** [spiral-project/ihatemoney#1019] opened 2022-04-26 22:16 UTC
There is a problem with to total displayed in statistics.
If i understood correctly : 
    - If Alice buy something 20 for Alice and Bob
    - Bob give her 10 for refund.
In theory, the total spend is 20 but ihatemoney will display 30 because the reimbursement is considered as an expense. The total will always be 1.5 * real value.
We should be able to "tag" the reimbursement in order not to take it into account in the total.

**Comment by dnshnrch** [comment] 2022-05-08 10:49
Was on holidays recently and stumbled over this issue as well. When looking into the statistics in my connected cospend instance within nextcloud, the reimbursement (provided the expense is tagged correctly) is considered correctly as your simple example shows.

**Comment by almet** [comment] 2022-05-08 13:19
Thanks for reporting this. Don't hesitate to propose a solution and open a pull request if you feel like it :-)

**Comment by gauthier12** [comment] 2022-05-10 07:40
@dnshnrch I don't understand if you are agreeing with me about the problem or if I missed something to "tag" the refund

**Comment by dnshnrch** [comment] 2022-05-10 08:50
@gauthier12 : I think we agree on the problem. In my case, when setting up a new project in Cospend (app within a nextcloud instance), there is a preconfigured category named "Erstattung" (engl.: 'Reimbursement'). Bobs reimbursement of 10 needs to be tagged accodingly and cospend will get the statistics right. The total amount of spent money should stay at 20 (which is, what Alice paid). 
But in MoneyBuster (AndroidApp for Cospend and ihatemoney) the total amount is 30. I added some screenshots to show the problem. 

Writing this, I hope the problem is clear, despite the fact, that this is maybe not directly ihatemoney related?  I don't now whether moneybuster and ihatemoney share the same code basis. 

@almet : Sorry, I'm only a user and not a programmer. I'm not able to lend a hand here :/

Expected behaviour:
![expected behaviour (Nextcloud CospendAPP)](https://user-images.githubusercontent.com/80472420/167588730-5a1cb2c4-06aa-451c-a505-06db834f62cd.jpg)

Wrong behaviour:
![wrong behaviour (MoneyBusterAndroidAPP)](https://user-images.githubusercontent.com/80472420/167588734-b42b4bf1-c7f6-420a-8956-4c3393f658a2.jpg)

**Comment by gauthier12** [comment] 2022-05-10 09:24
I have possible ideas for a solution but I am not competent with Python to implement it.
The solution would be to add a bool flag "refund" or "internal movement" and not take the expense into account in the sum if the the flag is set to true.
I realized that in triccount, there is this kind of flags : https://www.tricount.com/en/difference-expense-money-transfer-income  
with additional informations of expense/income/transfert

**Comment by ixcheldelsun** [comment] 2022-10-05 23:15
Hi, first time contributing to open source but I have DS and backend background to check this out. Still open?

**Comment by pH142857** [comment] 2022-10-17 08:23
> Hi, first time contributing to open source but I have DS and backend background to check this out. Still open?

Hi, I think it's still open, feel free to submit a PR :)

**Comment by kellikuramoto** [comment] 2022-11-29 03:00
My team would like to work on this issue! We are from CMU and contributing to an open source project is part of a class assignment.

**Comment by mvkashyap** [comment] 2022-12-04 23:48
Hi! I'm with @kellikuramoto 's group. We are considering adding a button on the Settle page so that the reimbursement doesn't affect the total spent. In other words, the bill will be settled on the settle page, and it won't show up on the bills tab, but it also will not contribute to the total spent.

**Comment by gauthier12** [comment] 2022-12-05 09:37
Can you do a "partial settle" e.g. I reimburse only a part or I lend money to someone?

**Comment by mvkashyap** [comment] 2022-12-06 20:22
@gauthier12 we are including a "type" of bill that is marked as a reimbursement. This type of bill would help settle other bills without adding to the total spent.

**Comment by Glandos** [comment] 2023-01-08 14:30
This is somewhat duplicate of #137

**Comment by zorun** [comment] 2024-04-12 09:37
Closing because #1290 has been merged

**Closed by zorun** 2024-04-12 09:37 UTC
