### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by 35609902357** [spiral-project/ihatemoney#522] opened 2019-12-28 17:16 UTC
The [website](https://ihatemoney.org/) does not have a privacy policy stating what and how data is collected, stored and eventually shared.

**Comment by almet** [comment] 2019-12-28 19:01
Thanks for taking the time to open this issue. I believe it's a duplicate of https://github.com/spiral-project/ihatemoney/issues/348, but still needs to be addressed!

**Closed by almet** 2019-12-28 19:01 UTC

**Comment by qoheniac** [comment] 2022-10-27 10:57
This issue was closed but I still cannot find a privacy policy.

**Comment by almet** [comment] 2022-11-07 23:11
Yes, please direct the discussion and efforts in #348. Cheers.
