### ISSUE TITLE
(sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by ghost** [spiral-project/ihatemoney#854] opened 2021-10-13 11:49 UTC
Hi, after making a clean install and start systemctl service I get this error: 

```
● ihatemoney.service - I hate money
     Loaded: loaded (/etc/systemd/system/ihatemoney.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-10-13 13:43:46 CEST; 6s ago
    Process: 1108755 ExecStart=/home/ihatemoney/ihatemoney/bin/gunicorn -c /etc/ihatemoney/gunicorn.conf.py ihatemoney.wsgi:application (code=exited, status=3)
   Main PID: 1108755 (code=exited, status=3)

Oct 13 13:43:46 zecircle.xyz ihatemoney[1108760]:     return dialect.connect(*cargs, **cparams)
Oct 13 13:43:46 zecircle.xyz ihatemoney[1108760]:   File "/home/ihatemoney/ihatemoney/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
Oct 13 13:43:46 zecircle.xyz ihatemoney[1108760]:     return self.dbapi.connect(*cargs, **cparams)
Oct 13 13:43:46 zecircle.xyz ihatemoney[1108760]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
Oct 13 13:43:46 zecircle.xyz ihatemoney[1108760]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
Oct 13 13:43:46 zecircle.xyz ihatemoney[1108760]: [2021-10-13 13:43:46 +0200] [1108760] [INFO] Worker exiting (pid: 1108760)
Oct 13 13:43:46 zecircle.xyz ihatemoney[1108755]: [2021-10-13 13:43:46 +0200] [1108755] [INFO] Shutting down: Master
Oct 13 13:43:46 zecircle.xyz ihatemoney[1108755]: [2021-10-13 13:43:46 +0200] [1108755] [INFO] Reason: Worker failed to boot.
Oct 13 13:43:46 zecircle.xyz systemd[1]: ihatemoney.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Oct 13 13:43:46 zecircle.xyz systemd[1]: ihatemoney.service: Failed with result 'exit-code'.
```

My config file:
```
# You can find more information about what these settings mean in the
# documentation, available online at
# http://ihatemoney.readthedocs.io/en/latest/installation.html#configuration

# Turn this on if you want to have more output on what's happening under the
# hood. DO NOT TURN IT ON IN PRODUCTION.
DEBUG = False

# The database URI, reprensenting the type of database and how to connect to it.
# Enter an absolute path here.
SQLALCHEMY_DATABASE_URI = 'sqlite:///home/ihatemoney/ihatemoney.db'
SQLACHEMY_ECHO = DEBUG

# Will likely become the default value in flask-sqlalchemy >=3 ; could be removed
# then:
SQLALCHEMY_TRACK_MODIFICATIONS = False

# This secret key is random and auto-generated, it protects cookies and user sessions
SECRET_KEY = "*****"

# A python tuple describing the name and email adress of the sender of the mails.
MAIL_DEFAULT_SENDER = ("Budget manager", "budget@notmyidea.org") # CUSTOMIZE

# If set to True, a demonstration project will be activated.
ACTIVATE_DEMO_PROJECT = False

# If not empty, the specified password must be entered to create new projects.
# DO NOT enter the password in cleartext. Generate a password hash with
# "ihatemoney generate_password_hash" instead.
ADMIN_PASSWORD = ""

# If set to True (default value) anyone can create a new project.
ALLOW_PUBLIC_PROJECT_CREATION = True

# If set to True, an administration dashboard is available.
ACTIVATE_ADMIN_DASHBOARD = False
```

**Comment by almet** [comment] 2021-10-13 15:46
When you have a `Bad Gateway` error it probably means that your reverse proxy is not configured properly. Can you paste your NGINX config here so we can help? Thanks

**Comment by almet** [comment] 2021-10-14 08:06
Obviously we also need to see gunicorn.conf.py

**Comment by almet** [comment] 2021-10-17 11:13
I'm closing this as it's not a bug in IHM but feel free to ping us if you need more help.

**Closed as completed by almet** 2021-10-17 11:13 UTC
