### ISSUE TITLE
Go responsive !

### ISSUE THREAD

**Issue by aavenel** [spiral-project/ihatemoney#113] opened 2013-10-12 15:12 UTC
ihatemoney is currently broken on mobile display. It's quite unusable even just to add a bill.

With all the improvements in bootstrap 3.0, it should be possible to provide a better experience !

Any thoughts about this ?

**Comment by ametaireau** [comment] 2015-04-16 13:14
I believe it's quite easy to accomplish, it's just a matter of updating the theme in order to have the latest bootstrap which is responsive.

**Comment by Vincent14** [comment] 2016-09-22 21:28
I agree, I need this!

**Comment by JocelynDelalande** [comment] 2016-09-23 15:25
@Vincent14 Feel free to submit a PR :-)

**Comment by almet** [comment] 2017-03-20 12:10
In case anyone is wondering, we now have bootstrap 4 support, but are not fully rezponsive yet!

**Comment by JocelynDelalande** [comment] 2017-03-31 15:06
@aavenel still interested to responsibilize ihatemoney now that it's using BS4 ? :-)

**Comment by Toover** [comment] 2017-04-10 11:54
As a new user, I was also deceived by the impossibility to use the web app on my mobile with the default configuration. I had to display it as if I was a computer, and in landscape mode, to workaround the issue where we cannot add a bill. However I don't care about seeing a "responsive design": fixing the issue is all this web app needs.

**Comment by almet** [comment] 2017-04-10 12:38
Thanks for taking the time to comment in here, feedback is always valuable.

You're right, this is problematic. The thing is that currently, nobody volunteered to make this happen, which is why you're facing the issue you're describing. If you want to help fix the issue or if you know someone who will be willing to, don't hesitate to propose some code changes, I'll happily review and eventually merge them.

**Comment by Toover** [comment] 2017-04-10 15:01
I have had a look around the code and it seems that a good solution would be to let the navigation bar to be to stay on top of the page, instead of floating on top of the view. Another one would be to make sure all buttons of the navigation bar are dropdown to save space, so that the current space calculation is right. Is there one of the solutions better than the other for you?

**Comment by almet** [comment] 2017-04-10 16:11
thanks for the proposition, I don't understand the proposition about the dropdown in order to save space, though.

The idea to not have the navigation bar on top might work, yes! It might also be possible to hack something together that would let it on mobile, but thiner in order to not get in the way. What do you think?

**Comment by Toover** [comment] 2017-04-10 17:11
About the drop down: the top navigation bar was always expanded, so it was covering the forms at the top of the page (like "add bill"). I figured out that with "bootstrap", you it is quite easy to have a drop-down menu that is collapsed by default, so that it only covers the top of the page when needed.

Diving into the issue and what the bootstrap framework issue, I figured out how to solve it without compromising the UI, so I'm on my way to committing and pull requesting =)

**Comment by almet** [comment] 2017-06-13 16:20
I think we should close this for now as ihatmeoney is not broken anymore on mobile display. If anyone wants to contribute a better way to be mobile compatible, please do open another ticket.

**Closed by almet** 2017-06-13 16:20 UTC
Labels: need contributor

**Comment by aavenel** [comment] 2017-06-13 19:17
Great work ! Is this deployed on ihatemoney.org ?

**Comment by almet** [comment] 2017-06-15 16:09
Did not get the time just yet :-)

**Comment by almet** [comment] 2017-06-20 12:05
Hi, I just deployed the latest version on ihatemoney.org, let me know if you find anything weird there :)
